name: dopedomains-net
services:
- name: web
  source_dir: /
  github:
    repo: your-username/dopedomains-net
    branch: main
  run_command: serve -s dist -l $PORT
  build_command: npm run build
  environment_slug: node-js
  instance_count: 2
  instance_size_slug: professional-xs
  http_port: 8080
  routes:
  - path: /
domains:
- domain: dopedomains.net
  type: PRIMARY
envs:
- key: NODE_ENV
  value: production

